services:
  postgres:
    image: postgres:16
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: diegosantanahost
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  diegosantanacalendar.api:
    image: ${DOCKER_REGISTRY-}diegosantanacalendarapi
    build:
      context: .
      dockerfile: DiegoSantanaCalendar.Api/Dockerfile
    depends_on:
      - postgres
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    ports:
      - "5000:5000"
      - "5001:5001"
    volumes:
      - ./DiegoSantanaCalendar.Api:/app
volumes:
  postgres_data:
  rabbitmq_data:
